---
- name: Check user input
  include_tasks: "init.yml"
  tags: [ always ]

- include_tasks: "docker.yml"
  tags: [ install ]

- name: Configure accounts
  tags: [ config ]
  template:
    dest: "{{ mail_persist_folder }}/config/postfix-accounts.cf"
    src: postfix-accounts.cf.j2
  register: accounts
  notify: Restart mail service

- name: Configure aliases
  tags: [ config ]
  template:
    dest: "{{ mail_persist_folder }}/config/postfix-virtual.cf"
    src: postfix-virtual.cf.j2
  notify: Restart mail service

- name: Configure send restrictions
  tags: [ config ]
  template:
    dest: "{{ mail_persist_folder }}/config/postfix-send-access.cf"
    src: postfix-send-access.cf.j2
  notify: Restart mail service

- name: Configure receive restrictions
  tags: [ config ]
  template:
    dest: "{{ mail_persist_folder }}/config/postfix-receive-access.cf"
    src: postfix-receive-access.cf.j2
  notify: Restart mail service

# MUST be run after accounts are configured
- include_tasks: docker-dkim.yml
  tags: [ config, dkim ]
  # when: accounts.changed
