---
- name: Restart cert renew
  become: yes
  systemd:
    daemon_reload: yes
    name: mail-certs-renew.timer
    state: restarted
    enabled: yes

- name: Restart mail service
  docker_container:
    name: mail-server
    restart: yes

- name: Create renew hook
  copy:
    dest: "{{ mail_persist_folder }}/certs/renewal-hooks/post/restart-mail-server.sh"
    mode: 0755
    content: |
      #!/usr/bin/env bash
      docker restart mail-server
